org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false

# Project Versions
plugin=6.0.0
minecraft=1.21.1
bukkit=1.20.1
forge=47.0.3
fabric-loader=0.15.11
fabric-api=0.100.8+1.21

# Is the project currently in a snapshot state?
snapshot = true
release-candidate = 0

# API Module Versions
core = 2.0.0
config = 2.0.0
commands = 2.0.0
libraries = 1.0.0
economy = 2.0.0
networking = 1.0.0
platform = 2.0.0
schedulers = 2.0.0
storage = 1.0.0
text = 2.0.0

adventure = 1.0.0
items = 2.0.0
nbt = 1.0.0