org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false

# Project Versions
plugin=5.3.2
minecraft=1.21.1
neoforge=21.1.66
fabric-loader=0.16.9
fabric-api=0.107.0+1.21.1

# Is the project currently in a snapshot state?
snapshot = true
release-candidate = 0
