org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false

# Project Versions
plugin=5.3.6
minecraft=26.1.2
neoforge=26.1.2.75
fabric-loader=0.18.4
fabric-api=0.151.0+26.1.2

# Is the project currently in a snapshot state?
snapshot = true
release-candidate = 0
