# +----------------------------------------------------------------------------------------------+
# |                                     Service Settings                                         |
# |                                                                                              |
# |     This section determines settings responsible for configuring the service available       |
# |     to Impactor's API.                                                                       |
# +----------------------------------------------------------------------------------------------+

# Indicates which service the Economy API should use. This should match the identifier used to suggest
# the service to the API at initialization time. If you're unaware of this identifier, you can observe
# suggested targets with this command:
#
# /economy service options
service = "impactor"