name: Verify License

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  check:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - name: Run License Check
        run: ./gradlew checkLicenses
  build:
    runs-on: ubuntu-20.04
    needs: check
    steps:
      - name: Build Project
        run: ./gradlew build
      - name: Archive artifacts for build
        uses: actions/upload-artifact@v2
        with:
          name: Impactor Jars
          path: |
            ${{ github.workspace }}/build/allJars/*.jar
