modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "impactor"
version = "${version}"
displayName = "Impactor"
description = '''

'''

[[mods]]
modId = "cloud"
version = "2.0.0+1.20-SNAPSHOT"
displayName = "Cloud Command Framework"
displayURL = "https://github.com/Incendo/cloud-forge"
authors = "Cloud Contributors"
description = "Cloud Command Framework on Forge"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.impactor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.impactor]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"