modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"

[[mods]]
modId = "impactor"
version = "${version}"
displayName = "Impactor"
description = '''

'''

[[dependencies.impactor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.impactor]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"